spring.application.name=findles

# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS (DOCKER)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5433/indexdb
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO JPA E HIBERNATE
# ==========================================
# Como estamos usando FLYWAY para gerenciar as tabelas, o Hibernate NÃO deve criar nada sozinho.
# Usamos "validate" apenas para ele conferir se as nossas classes Java batem com as tabelas do banco.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# CONFIGURAÇÕES DE SEGURANÇA (JWT)
# ==========================================
spring.api.security.token.secret=EstaSenhaEhMuitoForteEPrecisaTerNoMinimo32CaracteresFindles




