spring.application.name=findles

# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS (DOCKER)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5433/indexdb
spring.datasource.username=${POSTGRES_USER:root}
spring.datasource.password=${POSTGRES_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURAÇÕES DO JPA E HIBERNATE
# ==========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Liga o envio em lote
spring.jpa.properties.hibernate.jdbc.batch_size=1000
# Agrupa os UPDATEs em lote
spring.jpa.properties.hibernate.order_updates=true
# Agrupa os INSERTs em lote
spring.jpa.properties.hibernate.order_inserts=true

# ==========================================
# CONFIGURAÇÕES DE SEGURANÇA (JWT)
# ==========================================
spring.api.security.token.secret=${SECRET:secret}

# ==========================================
# CONFIGURAÇÕES DE ARQUIVOS (TAMANHO)
# ==========================================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ==========================================
# PAGINAÇÃO
# ==========================================

spring.data.web.pageable.one-indexed-parameters=true


