ALTER TABLE INDICE_INVERTIDO ALTER COLUMN TF_IDF SET DEFAULT 0.0;

INSERT INTO STATUS_CONSULTA (DESCRICAO) VALUES ('SUCESSO');
INSERT INTO STATUS_CONSULTA  (DESCRICAO) VALUES ('SEM RESULTADOS');
INSERT INTO STATUS_CONSULTA  (DESCRICAO) VALUES ('ERRO INTERNO');

ALTER TABLE documento ADD COLUMN MAGNITUDE_DOCUMENTO DOUBLE PRECISION DEFAULT 1.0;
