-- ==========================================
-- 1. TABELAS INDEPENDENTES (Sem chaves estrangeiras)
-- ==========================================

CREATE TABLE PERFIL_DE_USUARIO (
    ID_PERFIL_DE_USUARIO SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(150)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(150)
);

CREATE TABLE STATUS_DOCUMENTO (
    ID_STATUS_DOC SERIAL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(150)
);

CREATE TABLE STATUS_CONSULTA (
    ID_STATUS_CONSULTA SERIAL PRIMARY KEY,
    DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE TERMO (
    ID_TERMO SERIAL PRIMARY KEY,
    TERMO_NORMALIZADO VARCHAR(50) NOT NULL
);

-- ==========================================
-- 2. TABELAS DE PRIMEIRO NÍVEL DE DEPENDÊNCIA
-- ==========================================

CREATE TABLE USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    ID_PERFIL_DE_USUARIO INT NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    CADASTRADO_EM TIMESTAMP NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_PERFIL_DE_USUARIO) REFERENCES PERFIL_DE_USUARIO(ID_PERFIL_DE_USUARIO)
);

-- ==========================================
-- 3. TABELAS DE SEGUNDO NÍVEL DE DEPENDÊNCIA
-- ==========================================

CREATE TABLE AUDITORIA (
    ID_AUDITORIA SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ACAO VARCHAR(150) NOT NULL,
    DATA TIMESTAMP NOT NULL,
    LOG_ERRO TEXT, -- TEXT é o equivalente padrão ao varchar(max)
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE DOCUMENTO (
    ID_DOCUMENTO SERIAL PRIMARY KEY,
    ID_CATEGORIA INT, -- Nulo permitido conforme diagrama
    ID_INSERIDO_POR INT NOT NULL,
    ID_DOCUMENTO_ORIGEM INT, -- Nulo permitido (para indicar versão anterior)
    ID_STATUS_DOC INT NOT NULL,
    CAMINHO_ARQUIVO VARCHAR(255) NOT NULL,
    TITULO VARCHAR(50) NOT NULL,
    ATUALIZADO_EM TIMESTAMP NOT NULL,
    CRIADO_EM TIMESTAMP NOT NULL,
    HASH_CONTEUDO VARCHAR(100) NOT NULL,
    NUMERO_VERSAO VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
    FOREIGN KEY (ID_INSERIDO_POR) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_DOCUMENTO_ORIGEM) REFERENCES DOCUMENTO(ID_DOCUMENTO), -- Auto-relacionamento
    FOREIGN KEY (ID_STATUS_DOC) REFERENCES STATUS_DOCUMENTO(ID_STATUS_DOC)
);

CREATE TABLE CONSULTA (
    ID_CONSULTA SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_CATEGORIA INT, -- Nulo permitido
    ID_STATUS_CONSULTA INT NOT NULL,
    TEMPO_RESPOSTA_MS INT NOT NULL,
    DATA_CONSULTA TIMESTAMP NOT NULL,
    DATA_DE TIMESTAMP, -- Nulo permitido
    DATA_ATE TIMESTAMP, -- Nulo permitido
    QUANTIDADE_RESULTADO INT NOT NULL,
    AVALIACAO INT, -- Nulo permitido
    STRING_BUSCA VARCHAR(255) NOT NULL,
    ERRO TEXT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
    FOREIGN KEY (ID_STATUS_CONSULTA) REFERENCES STATUS_CONSULTA(ID_STATUS_CONSULTA)
);

-- ==========================================
-- 4. TABELAS DE TERCEIRO NÍVEL (Dependem de tabelas do nível 3)
-- ==========================================

CREATE TABLE RESULTADO (
    ID_RESULTADO SERIAL PRIMARY KEY,
    ID_CONSULTA INT NOT NULL,
    ID_DOCUMENTO INT NOT NULL,
    TRECHO_ENCONTRADO VARCHAR(255) NOT NULL,
    RELEVANCIA_SCORE INT NOT NULL,
    FOREIGN KEY (ID_CONSULTA) REFERENCES CONSULTA(ID_CONSULTA),
    FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID_DOCUMENTO)
);

CREATE TABLE INDICE_INVERTIDO (
    ID_INDICE_INVERTIDO SERIAL PRIMARY KEY,
    ID_DOCUMENTO INT NOT NULL,
    ID_TERMO INT NOT NULL,
    FREQUENCIA INT NOT NULL,
    TF_IDF FLOAT NOT NULL,
    FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID_DOCUMENTO),
    FOREIGN KEY (ID_TERMO) REFERENCES TERMO(ID_TERMO)
);